### ISSUE TITLE
[Discussion] Side effect using IdentityRepository for login

### ISSUE THREAD

**Issue by maxsitu** [dpalinic/public-transportation-services#12]
Hi @dpalinic , I am new to `lagom` and I'd like to confirm my thought about the snippet of code in [HERE](https://github.com/dpalinic/lagom-jwt-authentication/blob/master/identity-impl/src/main/scala/io/digitalcat/publictransportation/services/identity/impl/IdentityServiceImpl.scala#L59) , in order to improve my knowledge on `lagom framework`.

It seems like `loginUser` method is actually using `IdentityRepository` rather than asking `IdentityEntity` to check in local memory. Does that mean it's possible under high-traffic situation, service will return None after user being created. As at this point of time, events are still being processed in Read-Side processor while the new user is not reflected in repository's returning result.

I am curious if you ever thought about this concern, and what was your thinking process on this. (E.g. options you thought about and tradeoffs you considered)

Thanks for you help!

**Comment by dpalinic** [comment]
Hi @maxsitu , thanks for your message. 

Yes, you're correct. When user is created, he/she can't login until the event is propagated to the read side. The same is for all other requests going to read side. The time needed for synchronization to read side can be decreased with properties, and default is somewhere around 10 seconds (the shorted the value is, the more resources are taken for the synchronization).

I was following the pattern where all my read api requests are hitting the read side. If you make username as your id which can be used in `refFor`, you could ask it from write side I guess.

Hope this helps :) 

Regards

**Comment by maxsitu** [comment]
@dpalinic Thanks for your quick response again!On Apr 4, 2019 12:56 AM, Damir Palinic <notifications@github.com> wrote:Hi @maxsitu , thanks for your message.
Yes, you're correct. When user is created, it can't login until the event is not propagated to the read side. The same is for all other requests going to read side. The time needed for synchronization to read side can be decreased with properties, and default is somewhere around 10 seconds (the shorted the value is, the more resources are taken for the synchronization).
I was following the pattern where all my read api requests are hitting the read side. If you make username as your id which can be used in refFor, you could ask it from write side I guess.
Hope this helps :)
Regards

**Comment by dpalinic** [comment]
You're welcome @maxsitu :)

**Comment by maxsitu** [comment]
My concern was well-addressed with code owner's  explanation. I'm going to close this issue
